# Generated by Django 4.2.7 on 2023-11-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="glossaryentry",
            name="entry_sentence",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glossaryentry",
            name="from_seconds",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="glossaryentry",
            name="slug",
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="glossaryentry",
            name="to_seconds",
            field=models.IntegerField(null=True),
        ),
    ]
