# Generated by Django 4.2.7 on 2023-11-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("summery", "0002_glossaryentry_entry_sentence_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glossaryentry",
            options={"ordering": ["-from_seconds"]},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["-uploaded"]},
        ),
    ]
